Repository lionTestTeam25/25_Hours_test, pull requests merged in 2022-12, with the labels that each got.

#1 test pr
  .gitmessage.txt
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: bug

#10 <feat> : 회원가입 기능 구현
  youjin/youjin.md
Labels: help wanted

#9 <feat> : 로그인 기능 구현
  jisung/test.txt
Labels: bug

#15 <feat>:로그인 기능추가
  login/login.md
  로그인.md
Labels: documentation

#17 <docs> : 리드미 파일 추가
  jisungtest.txt
  youjin/youjin.md
  연습.md
Labels: documentation
